#!/bin/sh

readline_initialize()
{
  package_dependencies+=(ncurses)

  if package is active ncurses
  then
    package configure flags --with-curses
    debug package "Enabling 'termcap' support with 'ncurses'."
  elif package is active termcap
  then
    package configure flags --with-termcap
    debug package "Enabling 'termcap' support with 'termcap'."
  else
    warn "Termcap support disabled, install 'ncurses' or 'termcap' packages and reinstall 'readline' to enable."
  fi
}
